name: CI Build

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout GNSS_Tracker code
      uses: actions/checkout@v3
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:
          6.0.x
    
    - name: Build GNSS_Tracker
      run: dotnet build -c Release Source/GNSS_Tracker/GnssTracker.sln
