name: NuGet Package Creation

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set VERSION variable variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build -c Release ./Source/GnssTracker/GnssTracker.csproj /p:Version=${VERSION}
    - name: Pack
      run: dotnet pack -c Release ./Source/GnssTracker/GnssTracker.csproj /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Meadow.GnssTracker.${VERSION}.nupkg -s https://api.nuget.org/v3/index.json -k ${NUGET_TOKEN}
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
